# Generated by Django 4.2.13 on 2024-06-30 14:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'A quantidade de estrelas deve estar entre 0 e 5!'), django.core.validators.MaxValueValidator(5, 'A quantidade de estrelas deve estar entre 0 e 5!')])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='movies.movie')),
            ],
        ),
    ]
